### ISSUE TITLE
能否讲解一下你这套无服务器博客系统的使用方法

### ISSUE THREAD

**Issue by maboloshi** [banyudu/blog#13]
如题, 感觉内容源是基于`gist.github.com`

不胜感激

**Comment by maboloshi** [comment]
已经找到您写的教程正在拜读 https://gist.github.com/banyudu/d828d6e7d5ae7099f61c190da517890a

**Comment by banyudu** [comment]
> 如题, 感觉内容源是基于`gist.github.com`
> 
> 不胜感激

谢谢你的关注，这个系统目前主要还是个人在使用，不够成熟哈。我最近调研了一些CMS系统的设计，也有改造它的想法。

关于这个博客系统的设计理念，可以参考：https://banyudu.com/posts/create_blog_with_serverless_framework.854d58?random=FKXAL3 这个文章，对应的Gist是 https://gist.github.com/banyudu/854d58e541156b7884c76de5caac616b。

**Comment by banyudu** [comment]
现在主流的博客设计，本质上是CMS的设计。我在这个工程中试图使用Gist代替CMS，可以实现自动同步Gist中的文章，但是还没有把前后端分离，有些地方写死了个人的配置。

你有兴趣的话可以拿来参考，暂时还不具备直接使用的条件。

**Comment by maboloshi** [comment]
稍稍浏览了一下 大大超出了自己能看得懂的范围:sweat_smile:

期待楼主早日发布便于使用的版本
